pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                // Your build steps here
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing...'
                // Your test steps here
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Your deployment steps here
            }
        }
    }

    post {
        always {
            // always
        }
        success {
            // success
        }
        failure {
            // failure
        }
    }
}